/**
 * useWispcrew.ts — the renderer's single source of truth.
 *
 * All app state lives here: the agent roster, the selected agent, its
 * transcript, run state, settings, MCP servers, routines, and skills. The
 * hook subscribes once to the main process's push events and applies them
 * incrementally, so the UI updates at token speed without polling.
 *
 * Why one hook rather than a state library: the state is small, the update
 * rules are simple, and every mutation flows through the same bridge. Adding
 * Redux/Zustand here would be ceremony without benefit — and every dependency
 * in an app that executes shell commands is a supply-chain decision.
 */
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type {
  ConversationRecord,
  AgentRecord,
  AgentRunState,
  BridgeEvent,
  DetectedSignIn,
  McpServerStatus,
  NodeSummary,
  OAuthStatusView,
  PersonaView,
  PresetView,
  RoutineRecord,
  SettingsView,
  ContextReportView,
  SkillRecord,
  ToolGrant,
  TranscriptEntry,
} from '@wispcrew/shared';

/** Transcript entries capped in memory; the store keeps the durable history. */
const MAX_RENDERED_ENTRIES = 500;

export interface WispcrewState {
  ready: boolean;
  agents: AgentRecord[];
  selectedId: string | null;
  selected: AgentRecord | null;
  transcript: TranscriptEntry[];
  runState: AgentRunState;
  settings: SettingsView | null;
  presets: PresetView[];
  personas: PersonaView[];
  mcpServers: McpServerStatus[];
  /** Machines paired with this client; empty until the user attaches one. */
  nodes: NodeSummary[];
  routines: RoutineRecord[];
  skills: SkillRecord[];
  /** Transient banner messages (errors from the bridge, notices from main). */
  toast: { level: 'info' | 'error'; text: string } | null;
}

export function useWispcrew() {
  const [agents, setAgents] = useState<AgentRecord[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [transcript, setTranscript] = useState<TranscriptEntry[]>([]);

  /*
   * An entry shown before the engine has confirmed it.
   *
   * Prefixed rather than flagged, because it travels through the same
   * `TranscriptEntry` shape the rest of the code already handles — and a
   * real id is generated by the store, so this cannot collide.
   */
  const PENDING_PREFIX = 'pending_';
  const isPending = (entry: { id?: string }) => Boolean(entry.id?.startsWith(PENDING_PREFIX));
  /**
   * What the ENGINE says each agent is doing. Never written by the client.
   *
   * Keyed by agent id. A one-to-one conversation shares its agent's id, so
   * it reads directly; a group has an id of its own and is answered by
   * aggregating its members.
   */
  const [runStates, setRunStates] = useState<Record<string, AgentRunState>>({});

  /**
   * A conversation we have sent to and not yet heard the engine about.
   *
   * Covers one specific gap: `sendToRoom` for an agent on another machine
   * is a network round trip before anything is written, and without this
   * the composer would look idle while the message was in flight.
   *
   * Deliberately separate from `runStates`. It used to be written into that
   * map under the conversation id — harmless for a one-to-one, where the
   * engine's own `idle` for the same id cleared it, and permanent for a
   * group, whose `room_…` id the engine never emits. The Stop button stayed
   * live after both agents had finished.
   */
  const [awaitingEngine, setAwaitingEngine] = useState<string | null>(null);

  /**
   * How full the selected conversation's context is.
   *
   * Fetched rather than derived: the count has to include the system
   * prompt and the tool definitions, which live in the engine and never
   * reach the renderer. Null until the first answer arrives, so the meter
   * can stay absent rather than showing a confident zero.
   */
  const [contextReport, setContextReport] = useState<ContextReportView | null>(null);
  const [settings, setSettings] = useState<SettingsView | null>(null);
  const [presets, setPresets] = useState<PresetView[]>([]);
  const [personas, setPersonas] = useState<PersonaView[]>([]);
  const [mcpServers, setMcpServers] = useState<McpServerStatus[]>([]);
  const [nodes, setNodes] = useState<NodeSummary[]>([]);
  /*
   * Rooms, keyed the same way agents are.
   *
   * A migrated room reuses its agent id, so the current selection
   * identifies both and no second selector is needed.
   */
  const [conversations, setConversations] = useState<ConversationRecord[]>([]);
  const [routines, setRoutines] = useState<RoutineRecord[]>([]);
  const [skills, setSkills] = useState<SkillRecord[]>([]);
  const [grants, setGrants] = useState<ToolGrant[]>([]);
  const [oauthStatuses, setOauthStatuses] = useState<OAuthStatusView[]>([]);
  const [detectedSignIns, setDetectedSignIns] = useState<DetectedSignIn[]>([]);
  const [ready, setReady] = useState(false);
  const [toast, setToast] = useState<WispcrewState['toast']>(null);

  // The event handler needs the current selection without re-subscribing on
  // every change, so it reads from a ref rather than a closure capture.
  const selectedRef = useRef<string | null>(null);
  selectedRef.current = selectedId;

  // Actions need the current transcript without being rebuilt on every
  // streamed token, which would re-render the whole tree each frame.
  const transcriptRef = useRef<TranscriptEntry[]>([]);
  transcriptRef.current = transcript;

  const api = window.wispcrew;

  /** Surface an error to the user instead of losing it in the console. */
  /*
   * Swap one room in the list.
   *
   * These calls return the updated record, so refetching the whole
   * list would be a round trip for something already in hand.
   */
  const replaceRoom = useCallback(
    (updated: ConversationRecord | undefined) => (current: ConversationRecord[]) =>
      updated ? current.map((c) => (c.id === updated.id ? updated : c)) : current,
    [],
  );

  const fail = useCallback((err: unknown) => {
    const text = err instanceof Error ? err.message : String(err);
    setToast({ level: 'error', text });
  }, []);

  /**
   * The engine has said something about `id` — stop waiting on it.
   *
   * `id` is whatever the event carried: a conversation for a transcript
   * entry, an agent for a run-state. Either settles the wait, so both are
   * accepted and the conversation being awaited is resolved from its
   * membership.
   *
   * Reads the conversation list through a ref rather than closing over it,
   * so this callback stays stable and the event subscription is not town
   * down and rebuilt every time a room changes.
   */
  const conversationsRef = useRef<ConversationRecord[]>([]);

  const clearAwaiting = useCallback((id: string) => {
    setAwaitingEngine((current) => {
      if (!current) return current;
      if (current === id) return null;

      const room = conversationsRef.current.find((c) => c.id === current);
      const isMember = (room?.participants ?? []).some((p) => p.id === id);
      return isMember ? null : current;
    });
  }, []);

  /**
   * Take a whole conversation list, and keep the selection honest.
   *
   * One function because the two must happen together. The selection used to
   * be repaired inside the `agents-changed` handler, against the AGENT
   * roster — which was wrong twice over. A group is not in that roster, so a
   * group could be "repaired" away the moment any agent changed; and at
   * startup the roster event can land before the initial load, where an
   * empty selection was read as "deleted" and replaced with the first agent.
   *
   * The visible symptom was small and constant: the app opened on a row in
   * the middle of the sidebar rather than the one at the top.
   */
  const applyConversations = useCallback((list: ConversationRecord[]) => {
    // Mirrored into a ref so `clearAwaiting` can read membership without
    // closing over the list and forcing the event subscription to rebuild.
    conversationsRef.current = list;
    setConversations(list);
    setSelectedId((prev) => {
      if (prev && list.some((c) => c.id === prev)) return prev;
      // Newest first, which is the order the sidebar shows.
      return list[0]?.id ?? null;
    });
  }, []);

  /* -- initial load --------------------------------------------- */

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const [a, s, p, pe, m, r, sk, gr, oa, det, nd, cv] = await Promise.all([
          api.listAgents(),
          api.getSettings(),
          api.getPresets(),
          api.getPersonas(),
          api.listMcpServers(),
          api.listRoutines(),
          api.listSkills(),
          api.listToolGrants(),
          api.listOAuthStatus(),
          api.listDetectedCliSignIns(),
          api.listNodes(),
          api.listConversations(),
        ]);
        if (cancelled) return;
        // Defence in depth: main already repairs malformed stores, but a
        // non-array reaching a `.find`/`.map` here blanks the whole window
        // with only "find is not a function" in the console. Bad data must
        // degrade to an empty list, never a dead UI.
        const arr = <T,>(v: unknown): T[] => (Array.isArray(v) ? (v as T[]) : []);
        const agentList = arr<AgentRecord>(a);
        setAgents(agentList);
        setSettings(s);
        setPresets(arr<PresetView>(p));
        setPersonas(arr<PersonaView>(pe));
        setMcpServers(arr<McpServerStatus>(m));
        setRoutines(arr<RoutineRecord>(r));
        setSkills(arr<SkillRecord>(sk));
        setGrants(arr<ToolGrant>(gr));
        setOauthStatuses(arr<OAuthStatusView>(oa));
        setDetectedSignIns(arr<DetectedSignIn>(det));
        setNodes(arr<NodeSummary>(nd));
        /*
         * Open a CONVERSATION, not the first agent.
         *
         * The sidebar lists conversations, so defaulting to `agents[0]`
         * opened a row somewhere down the list — and a group, which has no
         * agent to be first, could never be the default at all.
         */
        applyConversations(arr<ConversationRecord>(cv));
        setReady(true);
      } catch (err) {
        if (!cancelled) {
          fail(err);
          setReady(true);
        }
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [api, fail, applyConversations]);

  /* -- push events ---------------------------------------------- */

  useEffect(() => {
    const off = api.onEvent((event: BridgeEvent) => {
      switch (event.type) {
        case 'transcript': {
          /*
           * A notice settles the wait, wherever it lands.
           *
           * A room turn can decide that NOBODY should speak — directed mode
           * with no mention — and say so in a notice. No agent runs, so no
           * run-state ever arrives, and without this the composer would
           * wait for an engine that had already finished answering.
           *
           * Checked before the visible-conversation filter below, because
           * the reply may arrive while the user is looking elsewhere.
           */
          if (event.entry.kind === 'notice') clearAwaiting(event.agentId);

          // Only the visible conversation is kept in renderer state; other
          // agents' entries are already persisted and load on selection.
          if (event.agentId !== selectedRef.current) return;
          setTranscript((prev) => {
            const idx = prev.findIndex((e) => e.id === event.entry.id);
            let next = idx === -1 ? [...prev, event.entry] : prev.slice();
            if (idx !== -1) next[idx] = event.entry;

            /*
             * Drop the optimistic copy once the real one lands.
             *
             * The placeholder exists so a message appears the instant it is
             * typed. For an agent on another machine the authoritative entry
             * only arrives after a round trip to that machine — which is why
             * the composer used to clear and nothing appear at all until the
             * reply came back.
             */
            if (
              event.entry.kind === 'message' &&
              (event.entry as { role?: string }).role === 'user'
            ) {
              const real = String((event.entry as { content?: unknown }).content ?? '');
              next = next.filter(
                (e) => !(isPending(e) && String((e as { content?: unknown }).content ?? '') === real),
              );
            }

            return next.length > MAX_RENDERED_ENTRIES
              ? next.slice(next.length - MAX_RENDERED_ENTRIES)
              : next;
          });
          return;
        }
        case 'run-state':
          setRunStates((prev) => ({ ...prev, [event.agentId]: event.state }));
          /*
           * The engine has spoken, so the optimistic flag has done its job.
           *
           * Cleared on a run-state and on a room NOTICE (below), and
           * deliberately NOT on the echo of the user's own message: that
           * arrives immediately even when the agent lives on another
           * machine, which is precisely the wait this flag exists to cover.
           */
          clearAwaiting(event.agentId);
          return;
        case 'agents-changed':
          setAgents(event.agents);

          /*
           * The rooms changed too. Deleting an agent removes it from every
           * conversation it had joined, so a sidebar that updated while the
           * room pane still listed the departed agent would be half fixed.
           *
           * Re-read rather than carry the rooms in the event: one frame
           * stays one fact, and the client asks for what that fact implies.
           *
           * The SELECTION is repaired from that answer, not from the roster
           * in this event — a group is not in the roster, so checking the
           * selection against it would throw the user out of a room every
           * time any agent changed.
           */
          void api.listConversations().then(applyConversations).catch(() => {
            // A refresh that fails leaves the previous list, which is stale
            // but coherent. The next event tries again.
          });
          return;
        case 'rooms-changed':
          /*
           * A room was renamed, re-moded, joined, left, or its greeting
           * edited — possibly from the CLI, possibly from another window.
           *
           * The list arrives in the frame rather than being re-fetched,
           * because the sender already has it and a round trip here would
           * leave a visible gap between the change and the screen catching
           * up.
           *
           * Through the same door as every other list, so a room deleted
           * elsewhere cannot leave the selection pointing at nothing.
           */
          applyConversations(event.conversations);
          return;
        case 'mcp-changed':
          setMcpServers(event.servers);
          return;
        case 'skills-changed':
          setSkills(event.skills);
          return;
        case 'routines-changed':
          setRoutines(event.routines);
          return;
        case 'grants-changed':
          setGrants(event.grants);
          return;
        case 'oauth-changed':
          setOauthStatuses(event.statuses);
          return;
        case 'notice':
          setToast({ level: event.level, text: event.text });
          return;
        default:
          return;
      }
    });
    return off;
  }, [api, applyConversations, clearAwaiting]);

  /* -- context meter -------------------------------------------- */

  /**
   * Re-measure when the selection changes, and after every turn.
   *
   * "After every turn" is what makes it useful: the number only moves when
   * something is said, and it is the moment somebody wants to know. Keyed
   * on the transcript length rather than a timer, so an idle window costs
   * nothing.
   *
   * Cleared first, so a stale figure from the previous conversation is
   * never shown against the new one — the same reason the transcript is
   * cleared before it is fetched.
   */
  useEffect(() => {
    if (!selectedId) {
      setContextReport(null);
      return;
    }

    let cancelled = false;
    void api
      .getContextReport(selectedId)
      .then((report) => {
        if (!cancelled && report?.conversationId === selectedId) setContextReport(report);
      })
      .catch(() => {
        // A measurement that fails is not worth a toast: the meter simply
        // keeps its last value, and the next turn tries again.
      });

    return () => {
      cancelled = true;
    };
    /*
     * Keyed on the transcript length, not the run state, which is declared
     * below this effect. The two move on the same beat — a finished turn
     * has written at least one entry — and using it here would mean
     * reordering the hooks, which is exactly the edit that blanked the
     * window once before.
     */
  }, [api, selectedId, transcript.length]);

  /* -- transcript loading on selection --------------------------- */

  useEffect(() => {
    if (!selectedId) {
      setTranscript([]);
      return;
    }

    /*
     * Clear before fetching, not after.
     *
     * Loading is asynchronous, so for as long as it takes the transcript
     * still holds the *previous* agent's messages. Streaming events for the
     * newly selected agent arrive in that window and were appended to them,
     * so switching mid-run showed two conversations spliced together — and
     * because the fetch then overwrote everything, whether you saw it
     * depended entirely on timing.
     *
     * Showing an empty conversation for a moment is honest; showing someone
     * else's messages is not.
     */
    setTranscript([]);

    let cancelled = false;
    void api
      .getTranscript(selectedId, MAX_RENDERED_ENTRIES)
      .then((entries) => {
        // A second switch while this was in flight must win, or the slower
        // request would clobber the newer agent's conversation.
        if (!cancelled) setTranscript(entries);
      })
      .catch(fail);
    return () => {
      cancelled = true;
    };
  }, [api, selectedId, fail]);

  /* -- auto-dismiss toasts --------------------------------------- */

  useEffect(() => {
    if (!toast) return;
    const t = setTimeout(() => setToast(null), toast.level === 'error' ? 8000 : 4000);
    return () => clearTimeout(t);
  }, [toast]);

  /* -- actions --------------------------------------------------- */

  const selected = useMemo(
    () => agents.find((a) => a.id === selectedId) ?? null,
    [agents, selectedId],
  );

  /**
   * The state of the conversation on screen.
   *
   * Run states are keyed by AGENT, and a direct chat shares its agent's id,
   * so that case reads straight off the map. A group has an id of its own
   * and no state of its own: it is busy when any member is, and waiting for
   * a decision outranks working — a header that says "working" while an
   * approval card sits unanswered hides the one state that needs the person.
   */
  const runState: AgentRunState = useMemo(() => {
    if (!selectedId) return 'idle';

    /*
     * The engine's answer wins, always.
     *
     * A one-to-one shares its agent's id, so it reads straight off the map.
     * A group has an id of its own and no state of its own: it is busy when
     * any member is, and waiting for a decision outranks working — a header
     * that says "working" while an approval sits unanswered hides the one
     * state that needs the person.
     */
    const own = runStates[selectedId];
    let worst: AgentRunState = own ?? 'idle';

    if (worst !== 'awaiting-approval') {
      const room = conversations.find((c) => c.id === selectedId);
      for (const p of room?.participants ?? []) {
        if (p.kind !== 'agent') continue;
        const s = runStates[p.id] ?? 'idle';
        if (s === 'awaiting-approval') return s;
        if (s !== 'idle' && worst === 'idle') worst = s;
      }
    }

    if (worst !== 'idle') return worst;

    /*
     * Only now the optimistic flag, and only for this conversation.
     *
     * It fills the gap between pressing Enter and the engine saying
     * anything — which for an agent on another machine is a round trip. It
     * can no longer outlive that gap, because it is not in `runStates` and
     * the first engine event clears it.
     */
    return awaitingEngine === selectedId ? 'thinking' : 'idle';
  }, [selectedId, runStates, conversations, awaitingEngine]);

  const actions = useMemo(
    () => ({
      /*
       * Selecting picks a CONVERSATION, not an agent.
       *
       * The id is the same thing for a direct chat — a migrated room reuses
       * its agent's id — but a group has an id of its own, and calling this
       * `selectAgent` was how a group ended up with no way to be opened.
       */
      selectConversation: setSelectedId,

      async createAgent(patch: Partial<AgentRecord> = {}) {
        try {
          const created = await api.createAgent(patch);

          /*
           * Add it to the roster in the same tick as selecting it.
           *
           * The roster is authoritative and arrives by `agents-changed`, but
           * that event lands a moment later. Selecting first left
           * `agents.find(...)` empty in between, so the chat pane rendered
           * "No agents yet" beside a sidebar that plainly had agents in it.
           *
           * Guarded against duplication: if the event has already arrived,
           * this is a no-op rather than a second copy.
           */
          setAgents((current) =>
            current.some((a) => a.id === created.id) ? current : [...current, created],
          );
          setSelectedId(created.id);
          return created;
        } catch (err) {
          fail(err);
          return null;
        }
      },

      async updateAgent(id: string, patch: Partial<AgentRecord>) {
        try {
          await api.updateAgent(id, patch);
        } catch (err) {
          fail(err);
        }
      },

      async deleteAgent(id: string) {
        try {
          await api.deleteAgent(id);
        } catch (err) {
          fail(err);
        }
      },

      async duplicateAgent(id: string) {
        try {
          await api.duplicateAgent(id);
        } catch (err) {
          fail(err);
        }
      },

      async send(prompt: string, attachmentPaths?: string[]) {
        if (!selectedRef.current) return;
        /*
         * Show the message, and that something is happening, immediately.
         *
         * `sendToRoom` for an agent on another machine is a whole round trip
         * before anything is written, so waiting for the authoritative entry
         * meant the composer cleared and the conversation stayed empty until
         * the reply arrived: the user typed, watched the text vanish, and
         * later saw an answer to a question that was never displayed.
         *
         * The placeholder is replaced by the real entry when it lands.
         */
        const target = selectedRef.current;
        setTranscript((prev) => [
          ...prev,
          {
            kind: 'message',
            id: `${PENDING_PREFIX}${Date.now()}`,
            role: 'user',
            content: prompt,
            createdAt: Date.now(),
          } as TranscriptEntry,
        ]);

        /*
         * Kept OUT of `runStates`, which belongs to the engine.
         *
         * This used to write `runStates[conversationId] = 'thinking'`. For a
         * one-to-one that is also the agent's id, so the engine's own
         * `idle` cleared it. In a group it is a `room_…` id the engine never
         * emits, so nothing ever cleared it: both agents finished, the panel
         * showed them listening, and the composer sat on "Agent is working"
         * with a live Stop button until the window was reloaded.
         *
         * Separating them means the authoritative map only ever holds what
         * the engine said, and this flag only covers the gap before it says
         * anything.
         */
        setAwaitingEngine(target);

        try {
          /*
           * Through the ROOM, so who acts follows the floor rules: a tagged
           * agent, everyone on `@all`, or whoever this person last
           * addressed. A room with one agent behaves exactly as before.
           */
          await api.sendToRoom(target, prompt, attachmentPaths);
        } catch (err) {
          /*
           * The send failed, so the placeholder is a lie: remove it rather
           * than leaving a message on screen that no agent ever received.
           */
          setTranscript((prev) => prev.filter((e) => !isPending(e)));
          setAwaitingEngine((current) => (current === target ? null : current));
          fail(err);
        }
      },

      /** Add an agent to the selected room. */
      async addRoomAgent(agentId: string) {
        if (!selectedRef.current) return;
        try {
          setConversations(replaceRoom(await api.addRoomAgent(selectedRef.current, agentId)));
        } catch (err) {
          fail(err);
        }
      },

      async removeRoomParticipant(participantId: string) {
        if (!selectedRef.current) return;
        try {
          setConversations(
            replaceRoom(await api.removeRoomParticipant(selectedRef.current, participantId)),
          );
        } catch (err) {
          fail(err);
        }
      },

      /*
       * Give a room its own name.
       *
       * Takes the id explicitly rather than reading the current selection:
       * the panel doing the renaming already knows which room it is
       * showing, and a rename that silently applied to whatever happened to
       * be selected would be a nasty way to lose one.
       */
      async renameConversation(conversationId: string, title: string) {
        try {
          setConversations(replaceRoom(await api.renameConversation(conversationId, title)));
        } catch (err) {
          fail(err);
        }
      },

      async setRoomMode(mode: string) {
        if (!selectedRef.current) return;
        try {
          setConversations(replaceRoom(await api.setRoomMode(selectedRef.current, mode as never)));
        } catch (err) {
          fail(err);
        }
      },

      /*
       * The room's standing instructions.
       *
       * Takes the id explicitly, like renaming: the pane editing it knows
       * which room it is showing, and instructions that silently landed on
       * whatever happened to be selected would be a nasty thing to discover
       * later.
       */
      async setRoomGreeting(conversationId: string, greeting: string) {
        try {
          setConversations(replaceRoom(await api.setRoomGreeting(conversationId, greeting)));
        } catch (err) {
          fail(err);
        }
      },

      /**
       * Remove a group.
       *
       * The whole list comes back, and goes through `applyConversations`,
       * which moves the selection off the room that no longer exists — a
       * deleted room left selected would render an empty chat with no
       * explanation.
       */
      async deleteRoom(conversationId: string) {
        try {
          applyConversations(await api.deleteRoom(conversationId));
        } catch (err) {
          fail(err);
        }
      },

      /**
       * Make a group, and select it.
       *
       * Selecting it is the point of doing it here: a room the user just
       * created and cannot see would look like a failure.
       */
      async createRoom(patch: {
        title: string;
        agentIds: string[];
        greeting?: string;
        fromConversationId?: string;
      }) {
        try {
          const room = await api.createRoom(patch);
          setConversations((current) => [room, ...current.filter((c) => c.id !== room.id)]);
          setSelectedId(room.id);
          return room;
        } catch (err) {
          fail(err);
          return undefined;
        }
      },

      pickFiles: api.pickFiles,

      async interrupt() {
        if (!selectedRef.current) return;
        try {
          await api.interrupt(selectedRef.current);
        } catch (err) {
          fail(err);
        }
      },

      async clearConversation() {
        if (!selectedRef.current) return;
        try {
          await api.clearConversation(selectedRef.current);
          setTranscript([]);
        } catch (err) {
          fail(err);
        }
      },

      /** Confirm Telegram works by sending a real message. */
      async testTelegram() {
        try {
          return await api.testTelegram();
        } catch (err) {
          return { ok: false, error: err instanceof Error ? err.message : String(err) };
        }
      },

      async discoverChatId() {
        try {
          return await api.discoverChatId();
        } catch {
          return null;
        }
      },

      /** Earlier versions of the selected conversation, newest first. */
      async listHistory() {
        if (!selectedRef.current) return [];
        try {
          return await api.listHistory(selectedRef.current);
        } catch (err) {
          fail(err);
          return [];
        }
      },

      /**
       * Put a saved version back.
       *
       * The restored entries come back from the call, so the view updates
       * without a second round trip — and without depending on an event that
       * a remote node would have to emit.
       */
      async restoreHistory(file: string) {
        if (!selectedRef.current) return false;
        try {
          const entries = await api.restoreHistory(selectedRef.current, file);
          setTranscript(Array.isArray(entries) ? entries : []);
          return true;
        } catch (err) {
          fail(err);
          return false;
        }
      },

      /**
       * Rewind, then optionally resend. `before` is "edit and retry": the
       * named message is dropped and its text handed back so the composer can
       * be prefilled, letting the user rephrase rather than retype.
       */
      async rewind(entryId: string, mode: 'through' | 'before') {
        const agentId = selectedRef.current;
        if (!agentId) return null;
        try {
          const removed =
            mode === 'before'
              ? transcriptRef.current.find((e) => e.id === entryId)
              : undefined;
          const kept = await api.rewindConversation(agentId, entryId, mode);
          setTranscript(Array.isArray(kept) ? kept : []);
          return removed && removed.kind === 'message' ? removed.content : null;
        } catch (err) {
          fail(err);
          return null;
        }
      },

      async branch(entryId: string) {
        const agentId = selectedRef.current;
        if (!agentId) return;
        try {
          const created = await api.branchConversation(agentId, entryId);
          setSelectedId(created.id);
          setToast({ level: 'info', text: `Branched into "${created.name}".` });
        } catch (err) {
          fail(err);
        }
      },

      async resolveApproval(requestId: string, resolution: 'allow-once' | 'allow-always' | 'deny') {
        try {
          await api.resolveApproval(requestId, resolution);
        } catch (err) {
          fail(err);
        }
      },

      async saveSettings(patch: Parameters<typeof api.saveSettings>[0]) {
        try {
          const next = await api.saveSettings(patch);
          setSettings(next);
          return next;
        } catch (err) {
          fail(err);
          return null;
        }
      },

      testConnection: api.testConnection,
      pickDirectory: api.pickDirectory,
      getAppInfo: api.getAppInfo,

      /**
       * Pair with a machine that is showing a code.
       *
       * Returns the error message rather than a boolean, because pairing
       * fails for reasons the user can act on — a mistyped code, an
       * unreachable host, a fingerprint that does not match — and "it didn't
       * work" would leave them guessing which.
       */
      async pairNode(address: string, code: string, expectFingerprint?: string) {
        try {
          await api.pairNode(address, code, expectFingerprint);
          setNodes(await api.listNodes());
          return null;
        } catch (err) {
          return err instanceof Error ? err.message : String(err);
        }
      },

      async forgetNode(nodeId: string) {
        try {
          setNodes(await api.forgetNode(nodeId));
          // Agents that lived there are now unreachable, so refresh the
          // roster to show it rather than leaving a stale "ready" state.
          setAgents(await api.listAgents());
          return true;
        } catch (err) {
          fail(err);
          return false;
        }
      },

      async refreshNodes() {
        try {
          setNodes(await api.listNodes());
        } catch (err) {
          fail(err);
        }
      },

      async addMcpServer(server: Parameters<typeof api.addMcpServer>[0]) {
        try {
          setMcpServers(await api.addMcpServer(server));
          return true;
        } catch (err) {
          fail(err);
          return false;
        }
      },

      async updateMcpServer(name: string, patch: Parameters<typeof api.updateMcpServer>[1]) {
        try {
          setMcpServers(await api.updateMcpServer(name, patch));
        } catch (err) {
          fail(err);
        }
      },

      async removeMcpServer(name: string) {
        try {
          setMcpServers(await api.removeMcpServer(name));
        } catch (err) {
          fail(err);
        }
      },

      async createRoutine(patch: Parameters<typeof api.createRoutine>[0]) {
        try {
          await api.createRoutine(patch);
        } catch (err) {
          fail(err);
        }
      },

      async updateRoutine(id: string, patch: Partial<RoutineRecord>) {
        try {
          await api.updateRoutine(id, patch);
        } catch (err) {
          fail(err);
        }
      },

      async deleteRoutine(id: string) {
        try {
          await api.deleteRoutine(id);
        } catch (err) {
          fail(err);
        }
      },

      async runRoutineNow(id: string) {
        try {
          await api.runRoutineNow(id);
        } catch (err) {
          fail(err);
        }
      },

      async createSkill(patch: Partial<SkillRecord>) {
        try {
          const created = await api.createSkill(patch);
          setSkills((prev) => [...prev, created]);
        } catch (err) {
          fail(err);
        }
      },

      async updateSkill(id: string, patch: Partial<SkillRecord>) {
        try {
          const updated = await api.updateSkill(id, patch);
          setSkills((prev) => prev.map((s) => (s.id === id ? updated : s)));
        } catch (err) {
          fail(err);
        }
      },

      async deleteSkill(id: string) {
        try {
          await api.deleteSkill(id);
          setSkills((prev) => prev.filter((s) => s.id !== id));
        } catch (err) {
          fail(err);
        }
      },

      /**
       * Sign-in actions return an error *message* rather than throwing, so
       * the settings panel can show it inline beside the button the user
       * just pressed instead of as a detached toast.
       */
      async oauthSignIn(vendor: 'anthropic' | 'chatgpt'): Promise<string | null> {
        try {
          await api.oauthSignIn(vendor);
          setOauthStatuses(await api.listOAuthStatus());
          setSettings(await api.getSettings());
          return null;
        } catch (err) {
          return err instanceof Error ? err.message : String(err);
        }
      },

      async oauthImport(vendor: 'anthropic' | 'chatgpt'): Promise<string | null> {
        try {
          await api.oauthImportFromCli(vendor);
          setOauthStatuses(await api.listOAuthStatus());
          setSettings(await api.getSettings());
          return null;
        } catch (err) {
          return err instanceof Error ? err.message : String(err);
        }
      },

      async oauthSignOut(vendor: 'anthropic' | 'chatgpt') {
        try {
          setOauthStatuses(await api.oauthSignOut(vendor));
          setSettings(await api.getSettings());
        } catch (err) {
          fail(err);
        }
      },

      async revokeGrant(agentId: string, toolName: string) {
        try {
          setGrants(await api.revokeToolGrant(agentId, toolName));
        } catch (err) {
          fail(err);
        }
      },

      async revokeAllGrants() {
        try {
          setGrants(await api.revokeAllToolGrants());
        } catch (err) {
          fail(err);
        }
      },

      dismissToast: () => setToast(null),
      notify: (text: string, level: 'info' | 'error' = 'info') => setToast({ level, text }),
    }),
    [api, fail, replaceRoom, applyConversations],
  );

  return {
    state: {
      ready,
      agents,
      selectedId,
      selected,
      transcript,
      runState,
      runStates,
      settings,
      presets,
      personas,
      mcpServers,
      nodes,
      conversations,
      contextReport,
      routines,
      skills,
      grants,
      oauthStatuses,
      detectedSignIns,
      toast,
    },
    actions,
  };
}
